# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               JCChen Blogger
description: '嗨~這裡是拿來記錄些技術性的東西(吧'
paginate: 10
url: "https://jcchen07944031.github.io/blogger//"

# About/contact
author:
  name:              JCChen
  url:               https://jcchen07944031.github.io/blogger/
  email:             james35022000@gmail.com

# Custom vars
version:             1.0.0
