# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:				JCChen Blogger
description:		'NCTU CS\nNTU INM'
baseurl: 			""
paginate: 			10
url: 				'https://jcchen07944031.github.io/blogger'
githuburl:			'https://github.com/jcchen07944031/'


# About/contact
author:
  name:              JCChen
  url:               https://jcchen07944031.github.io/blogger
  email:             james35022000@gmail.com

